# Generated by Django 3.2.9 on 2021-11-30 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcbar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workers',
        ),
    ]
